services:
  - type: web
    name: spin-win-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class gevent --bind 0.0.0.0:8080
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
